/* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */
/* Do not edit directly, auto-generated from: */
/*	Documentation/netlink/specs/netdev.yaml */
/* YNL-GEN uapi header */

#ifndef _UAPI_LINUX_NETDEV_H
#define _UAPI_LINUX_NETDEV_H

#define NETDEV_FAMILY_NAME	"netdev"
#define NETDEV_FAMILY_VERSION	1

enum netdev_xdp_feat {
	NETDEV_XDP_FEAT_ABORTED,
	NETDEV_XDP_FEAT_DROP,
	NETDEV_XDP_FEAT_PASS,
	NETDEV_XDP_FEAT_REDIRECT,
	NETDEV_XDP_FEAT_REDIRECT_TARGET,
	NETDEV_XDP_FEAT_SOCK_ZEROCOPY,
	NETDEV_XDP_FEAT_HW_OFFLOAD,
	NETDEV_XDP_FEAT_TX_LOCK,
	NETDEV_XDP_FEAT_FRAG_RX,
	NETDEV_XDP_FEAT_FRAG_TARGET,
};

enum {
	NETDEV_A_DEV_IFINDEX = 1,
	NETDEV_A_DEV_PAD,
	NETDEV_A_DEV_XDP_FEATURES,

	__NETDEV_A_DEV_MAX,
	NETDEV_A_DEV_MAX = (__NETDEV_A_DEV_MAX - 1)
};

enum {
	NETDEV_CMD_DEV_GET = 1,
	NETDEV_CMD_DEV_ADD_NTF,
	NETDEV_CMD_DEV_DEL_NTF,
	NETDEV_CMD_DEV_CHANGE_NTF,

	__NETDEV_CMD_MAX,
	NETDEV_CMD_MAX = (__NETDEV_CMD_MAX - 1)
};

#define NETDEV_MCGRP_MGMT	"mgmt"

#endif /* _UAPI_LINUX_NETDEV_H */
